command: ['streamlit', 'run', 'app.py', '--server.port=8000', '--server.address=0.0.0.0']

resources:
  - name: lakebase
    lakebase:
      endpoint: projects/healthcare-facility-finder/branches/production/endpoints/primary

env:
  - name: 'DATABRICKS_SERVER_HOSTNAME'
    value: 'dbc-816ff34d-b35d.cloud.databricks.com'
  - name: 'DATABRICKS_HTTP_PATH'
    value: '/sql/1.0/warehouses/serverless'
  - name: 'UC_CATALOG'
    value: 'main'
  - name: 'UC_SCHEMA'
    value: 'healthcare_facility_finder'
  - name: 'STREAMLIT_GATHER_USAGE_STATS'
    value: 'false'
  - name: 'STREAMLIT_BROWSER_GATHER_USAGE_STATS'
    value: 'false'